### ISSUE TITLE
Fatal error when installing the plugin with latest version of Kirby

### ISSUE THREAD

**Issue by raduhoria** [beebmx/kirby-db#4]
Fatal error: Cannot redeclare e() (previously declared in \vendor\illuminate\support\helpers.php:109) in \kirby\config\helpers.php on line 130

**Comment by beebmx** [comment]
Since [Kirby 3.7](https://getkirby.com/releases/3.7) all the helpers should be deactivated.

Here's the explanation for [deactivate globally](https://getkirby.com/docs/reference/templates/helpers#deactivate-a-helper-globally) every helper.

In short, you need to add this line of code (one or another):

```
const KIRBY_HELPER_E = false;

define('KIRBY_HELPER_E', false);
```
